### ISSUE TITLE
Fix color on chart if no vote for the note

### ISSUE THREAD

**Issue by shARPII** [captain-coaster/captain-coaster#102]
Example on twisted timbers, if there's 0 vote, it keeps the last color.
Imo the problem comes from the sql query. Right now, it will not create a line for a note if there is no vote for this one.
For the chart, we still need the value even if it's 0.

**Comment by richardcrete** [comment]
@shARPII maybe the chart should not be displayed if the the coaster is under consturction / announced or if there is no ratings:

<img width="317" alt="Screenshot 2024-01-06 à 16 51 29" src="https://github.com/captain-coaster/captain-coaster/assets/47246887/c44c9136-554f-4a87-8aac-7f96ddfda9e4">

https://captaincoaster.com/en/coasters/unnamed-stryker-coaster-nigloland

**Comment by shARPII** [comment]
> @shARPII maybe the chart should not be displayed if the the coaster is under construction / announced or if there is no ratings:
> <img alt="Screenshot 2024-01-06 à 16 51 29" width="317" src="https://private-user-images.githubusercontent.com/47246887/294700298-c44c9136-554f-4a87-8aac-7f96ddfda9e4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ1ODE3NDQsIm5iZiI6MTcwNDU4MTQ0NCwicGF0aCI6Ii80NzI0Njg4Ny8yOTQ3MDAyOTgtYzQ0YzkxMzYtNTU0Zi00YTg3LThhYWMtN2Y5NmRkZmRhOWU0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA2VDIyNTA0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY4NjY2YWIzZTk2MjE5ODhjZWI1NGU2ZmVlZjFmNWNlNDcwNmMzZTliYTFkZDIxYjJjNWQ5N2JhMmNiNDI3ZDImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.GhGIZPyuMU895lG59GeF0ki7dJZPYT-xeoQ81h3z8Nk">
> 
> https://captaincoaster.com/en/coasters/unnamed-stryker-coaster-nigloland

Yep I didn't see your message but I found it, I posted the PR if you want to check it as well so we make sure there is no other bugs @richardcrete . I fixed an other one if there's no reviews
