### ISSUE TITLE
A non-rateable coaster can be rate

### ISSUE THREAD

**Issue by richardcrete** [captain-coaster/captain-coaster#110]
Thanks to the coaster ID, a user could generate a link to the form review's page and rate a announced / under construction / rumored coaster. Example with:
https://captaincoaster.com/en/coasters/falcons-flight-six-flags-qiddiya
https://captaincoaster.com/en/reviews/coasters/5906/form

I think that an ajax call could also be made manually to rate a non-rateable coaster. We should add a verification with `coaster->isReatable()` in `rating_edit` route! What do you think @florian987 @shARPII?

- [ ] Fix form link
- [ ] Fix ajax call

**Comment by florian987** [comment]
well spotted!

make sure you are using a symfony voter for this:
https://symfony.com/doc/current/security/voters.html

(there are example on the project also)
