### ISSUE TITLE
Update API for coasters entity

### ISSUE THREAD

**Issue by exxodus** [captain-coaster/captain-coaster#36]
Some data define in the "coaster entity" are missing from the Captain Coaster API.  Like Train, Model, Launch, Restraint, Opening/Closing date, etc.  Could you update the API so we can get all thoses informations thru the already welcome API. 

Thanks.

**Comment by richardcrete** [comment]
We are going to remove the authentification system. The API has to be public.
The API will only contain public datas, no user datas.
We will give the World Ranking too.

**Comment by exxodus** [comment]
On a déjà le "world ranking" sur le coaster. Et pour moi l'authentification n'est pas un problème. J'aurais par contre aimer avoir le modèle, le Launch,  et le type de Restraint. Voir aussi le Pays sans devoir repasser par le parc. Et en ce qui concerne le parc, les corrd geographiques. 

Si non, super bon boulot que vous faites la !

**Comment by florian987** [comment]
Hi @exxodus, thanks for your interest in captain coaster!

I am getting back to dev, and I just added the missing data!

If you are building something cool with the API, please let us know :wink:
