### ISSUE TITLE
Langues du site

### ISSUE THREAD

**Issue by richardcrete** [captain-coaster/captain-coaster#44]
Nous devons ajouter l'Allemand, la plupart des traductions sont prêtes depuis longtemps.
Certaines traductions manquent en Français et en Espagnol (nom de pays, données de coaster...)

Nous devons ajouter des langages pour les avis, sans lien avec la langue du site (japonais, néerlandais...)

**Prio 1**

**Comment by florian987** [comment]
closing this one, because we split it into 2 issues
