### ISSUE TITLE
Filter closed parks from "Best amusement parks near"

### ISSUE THREAD

**Issue by aqwnji** [captain-coaster/captain-coaster#95]
On the park page, we can find the "Best amusement parks near", where the criteria is distance and having a coaster with sufficient score. However this includes closed coasters of the ranking.
The fix needed is to filter those closed coasters from the criteria (or add a status to the park based on the status of its coasters.)

**Comment by richardcrete** [comment]
@aqwnji shall we also not displaying the closest parks if the coasters of a park are closed?
