### ISSUE TITLE
EasyAdmin - Can't delete a coaster when a launch is defined

### ISSUE THREAD

**Issue by richardcrete** [captain-coaster/captain-coaster#96]
Error displayed in EasyAdmin :
> This item can't be deleted because other items depend on it.

Log example :
> EntityRemoveException: There is a ForeignKeyConstraintViolationException for the Doctrine entity associated with "Coaster". Solution: disable the "delete" action for this CRUD controller or configure the "cascade={"remove"}" attribute for the related field in the Doctrine entity. Full exception: An exception occurred while executing a query: SQLSTATE[23000]: Integrity constraint violation: 1451 Cannot delete or update a parent row: a foreign key constraint fails (captain.coaster_launch, CONSTRAINT FK_C678D027216303C FOREIGN KEY (coaster_id) REFERENCES coaster (id))

**Comment by florian987** [comment]
@richardcrete I made a fix, can you try again?

**Comment by richardcrete** [comment]
@florian987 it's working, thanks!
